services:
  execution:
    stop_grace_period: 30m
    container_name: gas-execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/besu/data
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
      - ${CHAINSPEC_PATH}:/tmp/chainspec/chainspec.json
    environment:
      BESU_USER_NAME: root
    user: root
    ports:
      - 8008:8008/tcp
      - 8545:8545
      - 8551:8551
    expose:
      - 8545
      - 8551
    command:
      - ${BESU_GENESIS_FLAG}
      - ${BESU_NETWORK_FLAG}
      - --bonsai-historical-block-limit=10000
      - --bonsai-limit-trie-logs-enabled=false
      - --data-path=/var/lib/besu/data
      - --metrics-enabled=true
      - --metrics-host=0.0.0.0
      - --metrics-port=8008
      - --engine-rpc-enabled=true
      - --engine-jwt-secret=/tmp/jwt/jwtsecret
      - --engine-rpc-port=8551
      - --engine-host-allowlist=*
      - --rpc-http-enabled=true
      - --rpc-http-host=0.0.0.0
      - --rpc-http-port=8545
      - --rpc-http-api=${EC_ENABLED_MODULES}
      - --rpc-http-cors-origins=*
      - --host-allowlist=*
      - --p2p-enabled=false
      - --max-peers=0
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    labels:
      metrics_enabled: "true"
      metrics_port: "8008"
      logs_enabled: "false"
      instance: "${GA_METRICS_LABELS_INSTANCE}"
  alloy:
    environment:
      METRICS_LABELS_EXECUTION_CLIENT: "besu"
    extends:
      file: ../addons/alloy/compose.yaml
      service: alloy
networks:
  gas:
    name: gas-network
    internal: true
