services:
  execution:
    stop_grace_period: 30m
    container_name: gas-execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - execution_data:/var/lib/nimbus/data
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
    user: root
    ports:
      - 8008:8008/tcp
      - 8545:8545
      - 8551:8551
    expose:
      - 8545
      - 8551
    command:
      - ${NIMBUS_NETWORK_FLAG:---custom-network=/tmp/genesis/genesis.json}
      - --data-dir=/var/lib/nimbus/data
      - --metrics=true
      - --metrics-address=0.0.0.0
      - --metrics-port=8008
      - --engine-api=true
      - --max-peers=0
      - --jwt-secret=/tmp/jwt/jwtsecret
      - --engine-api-port=8551
      - --engine-api-address=0.0.0.0
      - --allowed-origins=*
      - --rpc=true
      - --http-address=0.0.0.0
      - --http-port=8545
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
networks:
  gas:
    name: gas-network
volumes:
  execution_data:
    name: ${EC_VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      o: bind,rw,dirsync,noatime
      device: ${EC_DATA_DIR}
