services:
  execution:
    stop_grace_period: 30m
    container_name: gas-execution-client
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/nimbus/data
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
    user: root
    ports:
      - 30303:30303/tcp
      - 30303:30303/udp
      - 8008:8008/tcp
      - 8545:8545
      - 8551:8551
    expose:
      - 8545
      - 8551
    command:
      - --custom-network=/tmp/genesis/genesis.json
      - --data-dir=/var/lib/nimbus/data
      - --metrics=true
      - --metrics-address=0.0.0.0
      - --metrics-port=8008
      - --engine-api=true
      - --max-peers=0
      - --jwt-secret=/tmp/jwt/jwtsecret
      - --engine-api-port=8551
      - --engine-api-address=0.0.0.0
      - --allowed-origins=*
      - --rpc=true
      - --http-address=0.0.0.0
      - --http-port=8545
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    labels:
      metrics_enabled: "true"
      metrics_port: "8008"
      metrics_path: "/metrics"
      logs_enabled: "false"
      instance: "${GA_METRICS_LABELS_INSTANCE}"
  alloy:
    environment:
      METRICS_LABELS_EXECUTION_CLIENT: "nimbus-el"
    extends:
      file: ../addons/alloy/compose.yaml
      service: alloy
  node-exporter:
    extends:
      file: ../addons/node-exporter/compose.yaml
      service: node-exporter
networks:
  gas:
    name: gas-network
