services:
  execution-sync:
    user: "root:root"
    container_name: gas-execution-client-sync
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - execution_data:/data
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
      - ${EC_JWT_SECRET_PATH}:/tmp/jwtsecret
    entrypoint:
      - /bin/sh
      - -c
      - ${ERIGON_INIT_COMMAND}
  execution:
    user: "root:root"
    stop_grace_period: 30m
    container_name: gas-execution-client
    depends_on:
      execution-sync:
        condition: service_completed_successfully
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - execution_data:/data
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
      - ${EC_JWT_SECRET_PATH}:/tmp/jwtsecret
    ports:
      - "8008:8008/tcp"
      - "8551:8551"
      - "8545:8545"
    command:
      - --datadir=/data
      - --nat=none
      - --maxpeers=0
      - --txpool.disable
      - --nodiscover
      - --no-downloader
      - --torrent.download.rate=0
      - --torrent.upload.rate=0
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=web3,eth,net,engine,debug
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/tmp/jwtsecret
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=8008
      - --prune.mode=full
      - --log.dir.disable
      - --private.api.addr=0.0.0.0:9090
      - --externalcl
      - --fcu.timeout=0
      - --fcu.background.prune=false
      - --fcu.background.commit=false
      - --sync.parallel-state-flushing=false
      - ${ERIGON_CHAIN_FLAG}
      - --log.console.verbosity=debug
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    labels:
      metrics_enabled: "true"
      metrics_port: "8008"
      metrics_path: "/debug/metrics/prometheus"
      logs_enabled: "false"
      instance: "${GA_METRICS_LABELS_INSTANCE}"
  alloy:
    environment:
      METRICS_LABELS_EXECUTION_CLIENT: "erigon"
    extends:
      file: ../addons/alloy/compose.yaml
      service: alloy
  node-exporter:
    extends:
      file: ../addons/node-exporter/compose.yaml
      service: node-exporter
networks:
  gas:
    name: gas-network
volumes:
  execution_data:
    name: ${EC_VOLUME_NAME}
    driver: local
    driver_opts:
      type: none
      o: bind,rw,dirsync,noatime
      device: ${EC_DATA_DIR}
