services:
  execution-sync:
    user: "root:root"
    container_name: gas-execution-client-sync
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/erigon
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
    entrypoint:
      - /bin/sh
      - -c
      - ${ERIGON_INIT_COMMAND}
  execution:
    user: "root:root"
    stop_grace_period: 30m
    container_name: gas-execution-client
    depends_on:
      execution-sync:
        condition: service_completed_successfully
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/erigon
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
      - "8008:8008/tcp"
      - "8551:8551"
    command:
      - ${ERIGON_CHAIN_FLAG}
      - --externalcl
      - --private.api.addr=0.0.0.0:9090
      - --nat=any
      - --p2p.disable
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=web3,eth,net,engine
      - --txpool.disable
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/tmp/jwt/jwtsecret
      - --datadir=/var/lib/erigon
      - --healthcheck
      - --metrics
      - --metrics.addr=0.0.0.0
      - --metrics.port=8008
      - --db.size.limit=2GB
      - --experimental.always-generate-changesets
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    labels:
      metrics_enabled: "true"
      metrics_port: "8008"
      logs_enabled: "false"
      instance: "${GA_METRICS_LABELS_INSTANCE}"
  alloy:
    environment:
      METRICS_LABELS_EXECUTION_CLIENT: "erigon"
      METRICS_ENDPOINT_PATH: "/debug/metrics/prometheus"
    extends:
      file: ../addons/alloy/compose.yaml
      service: alloy
networks:
  gas:
    name: gas-network
    internal: true
