services:
  execution-sync:
    container_name: gas-execution-client-sync
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/reth
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
    entrypoint:
      - /bin/sh
      - -c
      - ${RETH_INIT_COMMAND}
  execution:
    stop_grace_period: 30m
    container_name: gas-execution-client
    depends_on:
      execution-sync:
        condition: service_completed_successfully
    restart: unless-stopped
    image: ${EC_IMAGE_VERSION}
    pull_policy: always
    networks:
      - gas
    volumes:
      - ${EC_DATA_DIR}:/var/lib/reth
      - ${GENESIS_PATH}:/tmp/genesis/genesis.json
      - ${EC_JWT_SECRET_PATH}:/tmp/jwt/jwtsecret
    ports:
      - "8008:8008/tcp"
      - "8551:8551"
      - "8545:8545"
    expose:
      - 8545
      - 8546
      - 8551
    command:
      - node
      - --datadir=/var/lib/reth
      - ${RETH_CHAIN_ARG}
      - --http
      - --http.addr=0.0.0.0
      - --http.api=web3,eth,net
      - --http.port=8545
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=admin,debug,eth,net,trace,txpool,web3,rpc,reth,ots,flashbots,miner,mev
      - --authrpc.jwtsecret=/tmp/jwt/jwtsecret
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    labels:
      metrics_enabled: "true"
      metrics_port: "8008"
      logs_enabled: "false"
      instance: "${GA_METRICS_LABELS_INSTANCE}"
  alloy:
    environment:
      METRICS_LABELS_EXECUTION_CLIENT: "reth"
      METRICS_ENDPOINT_PATH: "/debug/metrics/prometheus"
    extends:
      file: ../addons/alloy/compose.yaml
      service: alloy
networks:
  gas:
    name: gas-network
    internal: true
