name: Run Nethermind Benchamarks

on:
  workflow_dispatch:
    inputs:
      how_many_runs:
        description: 'Number of times to run the tests'
        default: '4'
      folder:
        description: 'Folder in which the tests are stored'
        default: 'tests'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_INSTALL_DIR: "~/.dotnet"
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: "8.0.x"

    - name: Install python dependencies
      run: pip install -r requirements.txt

    - name: Prepare nethermind dependencies
      run: make prepare_nethermind

    - name: Create results directory
      run: mkdir results

    - name: Run Python Script
      run: python benchmarker.py --client nethermind --numberOfRuns ${{ github.event.inputs.how_many_runs }} --testsPath /home/runner/work/gas-benchmarks/gas-benchmarks/${{ github.event.inputs.folder }} --dotnetPath ~/.dotnet/dotnet

    - name: Zip the results folder
      run: zip -r results.zip results

    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      with:
        name: results-archive
        path: results.zip